baseURL = "https://www.yabai.it/"
languageCode = "en-us"
title = "Yabai"
theme = "beautifulhugo"

[outputs]
home = [ "HTML", "RSS", "REDIR" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = ["redir"]

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
